# Deployment for the data logger python script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: https-server
  template:
    metadata:
      labels:
        app: https-server
    spec:
      containers:
        - name: https-server
          image: image-registry.apps.2.rahti.csc.fi/protocol-measurements/https-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "4000m"
              memory: "6000Mi"
            requests:
              cpu: "1000m"
              memory: "3000Mi"
          envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets
          env: # environment variables for the container
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: "TSDB_BUCKET"
              value: "http2_bucket0"
            - name: "LOG_FILE_PATH"
              value: "/tmp/log.txt"
            - name: CERT_PATH
              value: "/certs" 
          volumeMounts: # link to configmap / secret, and set the paths
            - name: https-certs
              mountPath: /certs
        - name: vnstat
          image: vergoh/vnstat:latest
          volumeMounts:
            - name: net-out
              mountPath: /metrics
          env:
            - name: IFACE
              value: "eth0"
          command:
            - sh
            - -c
            - |
              echo "timestamp,rx_kbit_s,tx_kbit_s" > /metrics/vnstat.csv

              while true; do
                # 1-second measurement window; prints avg rates for that second
                json=$(vnstat -tr 1 -i "$IFACE" --json)

                ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)

                # extract the first "rx" value from JSON by stripping everything except numbers
                rx=$(echo "$json" | awk -F'[,:}]' '/"rx":/ {gsub(/[^0-9.]/,"",$3); print $3; exit}')

                # extract the first "tx" value from JSON by stripping everything except numbers
                tx=$(echo "$json" | awk -F'[,:}]' '/"tx":/ {gsub(/[^0-9.]/,"",$3); print $3; exit}')

                # write data row to CSV, insert 0 if extract failed
                printf "%s,%s,%s\n" "$ts" "${rx:-0}" "${tx:-0}" >> /metrics/vnstat.csv
              done
      volumes: # definition for volumes used for the pod
        - name: https-certs
          secret:
            secretName: certs
        - name: net-out
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: https-service
  namespace: protocol-measurements
  annotations:
     metallb.universe.tf/allow-shared-ip: "label-to-share-1.2.3.4"
spec:
  ports:
    - name: http
      protocol: TCP
      port: 30686
      targetPort: 8000
    - name: iperf3-tcp # open port for iperf3 server inside same pod
      protocol: TCP
      port: 30687
      targetPort: 5201
  allocateLoadBalancerNodePorts: false
  type: LoadBalancer
  selector:
    app: https-server # link service to all pods

---
